/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ActionConnector) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AlertingRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecurityRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SLO) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Space) Hub() {}
