apiVersion: kibana.justtrack.io/v1alpha1
kind: SecurityRole
metadata:
  annotations:
    meta.upbound.io/example-id: kibana/v1alpha1/securityrole
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    elasticsearch:
    - cluster:
      - create_snapshot
      indices:
      - fieldSecurity:
        - except: []
          grant:
          - test
        names:
        - test
        privileges:
        - create
        - read
        - write
    kibana:
    - base:
      - all
      spaces:
      - default
    name: sample_role
