/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AgentPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Integration) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IntegrationPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Output) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServerHost) Hub() {}
