apiVersion: fleet.justtrack.io/v1alpha1
kind: IntegrationPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: fleet/v1alpha1/integrationpolicy
  labels:
    testing.upbound.io/example-name: sample
  name: sample
spec:
  forProvider:
    agentPolicyId: ${elasticstack_fleet_agent_policy.sample.policy_id}
    description: A sample integration policy
    input:
    - inputId: tcp-tcp
      streamsJsonSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
    integrationName: tcp
    integrationVersion: 1.16.0
    name: Sample Integration Policy
    namespace: default

---

apiVersion: fleet.justtrack.io/v1alpha1
kind: AgentPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: fleet/v1alpha1/integrationpolicy
  labels:
    testing.upbound.io/example-name: sample
  name: sample
spec:
  forProvider:
    description: A sample agent policy
    monitorLogs: true
    monitorMetrics: true
    name: Sample Agent Policy
    namespace: default
    skipDestroy: false

---

apiVersion: fleet.justtrack.io/v1alpha1
kind: Integration
metadata:
  annotations:
    meta.upbound.io/example-id: fleet/v1alpha1/integrationpolicy
  labels:
    testing.upbound.io/example-name: sample
  name: sample
spec:
  forProvider:
    force: true
    name: tcp
    version: 1.16.0
